# Analyze platform performance
# Q1. What is the total revenue earned by the food delivery app ?
select sum((total_expense-commission)) as Revenue 
from monthly_member_totals;

# Q2. What is the monthly revenue earned by the food delivery app ?
select month,sum((total_expense-commission)) as Revenue 
from monthly_member_totals
group by month
order by revenue desc;


# Identify popular regions, meals, and restaurant categories among customers
# Q3. Which are the most popular restaurants?
select  restaurant_name,count(o.id) as Order_frequency
from restaurants r
join orders o
on r.id=o.restaurants_id
group by restaurant_name
order by Order_frequency desc limit 10;

# Q4. Which are the popular restaurant categories(restaurant types) ?
select  restaurant_types,count(o.id) as Order_frequency
from restaurant_types rt
join restaurants r
on rt.id=r.restaurant_types_id
join orders o
on r.id=o.restaurants_id
group by restaurant_types
order by Order_frequency desc ;

# Q5. Which are the popular meal types ?
select  meal_type,count(od.id) as Order_frequency
from meal_types mt
join meals m
on mt.id=m.meal_types_id
join order_details od
on m.id=od.meals_id
group by meal_type
order by Order_frequency desc ;

# Q6. Which are the popular meals ?
select meal_name,count(orders_id) as Order_frequency from order_details
join meals
on meals.id=order_details.meals_id
group by meals_id 
order by Order_frequency desc limit 5;

# Q7. Which are the best-performing restaurants in terms of orders placed in each restaurant category ?
WITH Top_rest_categorywise AS (
    SELECT  
        restaurant_types , 
       restaurant_name,
	   count(o.id) as order_count
    FROM restaurant_types rt
    JOIN restaurants r
        ON rt.id = r.restaurant_types_id
	join orders o
    on r.id=o.restaurants_id
    group by restaurant_name,restaurant_types
)
SELECT *
FROM (
    SELECT 
        restaurant_types,
       restaurant_name,
        order_count,
         DENSE_RANK() OVER (
            PARTITION BY restaurant_types
            ORDER BY order_count DESC
        ) AS rnk
    FROM Top_rest_categorywise
) t
WHERE rnk <= 3;

# Q8. Which cities show the highest customer demand based on order frequency?
With City_Orders AS 
(select c.city as City ,o.id as order_id
from cities c
inner join restaurants r
on c.id=r.cities_id
inner join orders o
on r.id=o.restaurants_id)

select City,count(order_id) as num_of_orders
from City_Orders 
group by City 
order by num_of_orders desc;


# Detect loyal customers
# Q9. Identify the most profitable customers for platform in terms of revenue generated by a customer.
select concat(first_name," ",surname) as name,sum((total_expense-commission)) as Revenue 
from monthly_member_totals
group by name
having Revenue>4500
order by revenue desc;

# Q10. Identify the customers who frequently place orders.
select  concat(m.first_name," ",m.surname) as customer_name, sum(order_count) as Total_times_order,m.sex
from members m
inner join monthly_member_totals mmt
on m.id=mmt.members_id
group by m.id
having Total_times_order>=150
order by Total_times_order desc;

# Q11. Who are the top 5 most active customers each month based on order frequency?
WITH Monthwise_top_customer AS (
    SELECT  
        CONCAT(m.first_name, ' ', m.surname) AS customer_name, 
        mmt.order_count,
        mmt.month
    FROM members m
    JOIN monthly_member_totals mmt
        ON m.id = mmt.members_id
)

SELECT *
FROM (
    SELECT 
        customer_name,
        month,
        order_count,
         DENSE_RANK() OVER (
            PARTITION BY month 
            ORDER BY order_count DESC
        ) AS rnk
    FROM Monthwise_top_customer
) t
WHERE rnk <= 5;


# Understand ordering patterns (time, gender, behaviour) and restaurant pricing patterns
# Q12. What are peak ordering hours ?
select  hour(hour) as hours,
		count(id) as no_of_orders
from orders 
group by hours
order by no_of_orders desc ;

# Q13. Do males or females place higher no. of orders ?
select sex, count(o.id) as total_orders
from members m
join orders o
on m.id=o.members_id
group by sex
order by total_orders desc;

# Q14. Which are the popular restaurants among a particular gender?
with Rest_Members as
(select sex,count(o.id) as total_orders ,restaurant_name,city
from members m
join orders o 
on m.id=o.members_id
join restaurants r
on o.restaurants_id=r.id
join cities c
on c.id=r.cities_id
group by sex,restaurant_name,city
)
select * 
from( select  
             sex,
			 restaurant_name,
             city,
             total_orders,
             dense_rank() over(
                               partition by sex
                               order by total_orders desc
                               ) as rnk
from Rest_Members) t
where rnk<=10 ;

# Q.15 Are the same restaurant categories popular among both the genders ? 
with Rest_Members as
(select sex,count(o.id) as total_orders ,restaurant_types
from members m
join orders o 
on m.id=o.members_id
join restaurants r
on o.restaurants_id=r.id
join restaurant_types rt
on r.restaurant_types_id=rt.id
group by sex,restaurant_types
)
select * 
from( select  
             sex,
			 restaurant_types,
             total_orders,
             dense_rank() over(
                               partition by sex
                               order by total_orders desc
                               ) as rnk
from Rest_Members) t
where rnk<=5 ;

# Q16. Is there a difference in the gender wise preference of meals ?
with mealstype_gender as
(select sex,count(o.id) as total_orders ,meal_type
from members m
join orders o 
on m.id=o.members_id
join order_details od
on o.id=od.orders_id
join meals me
on me.id=od.meals_id
join meal_types mt
on mt.id=me.meal_types_id
group by sex,meal_type
)
select * 
from( select  
             sex,
			 meal_type,
             total_orders,
             dense_rank() over(
                               partition by sex
                               order by total_orders desc
                               ) as rnk
from mealstype_gender) t
where rnk<=5 ;

# Q17. How many meals are ordered per order on an average ?
with mealcount_per_order as
(select orders_id,(count(meals_id)) as total_meals
from order_details
group by orders_id)

select avg(total_meals) as avg_meals_per_order
from  mealcount_per_order;

# Q18. What is the average order price ? 
select round(avg(total_order),2) as avg_price from orders;

# Q19. Which are the high-end and budget friendly restaurants as per average order price ?
with avg_order_price as
(
select 
       restaurant_name,total_order,city
from orders o 
join restaurants r
on o.restaurants_id=r.id
join cities c
on c.id=r.cities_id
)
select restaurant_name, avg(total_order) as avg_price ,city
from avg_order_price
group by restaurant_name,city
order by avg_price desc;

# Q20. Identify budget-friendly and premium meals as per average meal price.
with avg_meal_price as
(
select 
       meal_type,total_order
from orders o 
join order_details od
on o.id=od.orders_id
join meals me
on me.id=od.meals_id
join meal_types mt
on me.meal_types_id=mt.id
)
select meal_type, avg(total_order) as avg_price
from avg_meal_price
group by meal_type
order by avg_price desc;


# Evaluate customer's spending behaviour
# Q21. Which customers exceed their budget ?
with customer_budget as (
select concat(first_name," ",surname) as name ,monthly_budget as target , total_expense as actual_spending 
from monthly_member_totals mmt)
select  name , target , actual_spending ,
(target-actual_spending) as target_actual
from customer_budget
order by target_actual ;


# Understand restaurants' performance
# Q22. Which are the restaurants that earn high revenue in terms of income percentage / earn the highest payout ?
with restaurant_order_price as
(
select restaurant_name, sum(total_order) as total_order_price,max(income_percentage) as inc_pct
from
orders o 
join restaurants r
on o.restaurants_id=r.id
group by restaurant_name
order by total_order_price desc)

select restaurant_name,total_order_price,round((total_order_price*inc_pct),2) as Revenue from restaurant_order_price 
order by Revenue desc limit 10;
